
export const routes = {
  moneyMutt:{
    dashboard:'/dashboard',
    signIn: '/signin',
    profileSettings: 'dashboard/profile-settings/profile',
    notificationPreference: 'dashboard/profile-settings/notification',
    personalInformation: 'dashboard/profile-settings/profile',
    password: 'dashboard/profile-settings/password',
    newsletter: 'dashboard/newsletter',
    createProduct :'/dashboard/audience/create',
    ediProduct: (slug: string) => `/dashboard/audience/${slug}/edit`,
    audience : '/dashboard/audience',
    companyDetails:'/dashboard/profile-settings/team',
    billing:'/dashboard/profile-settings/billing',
    team : '/dashboard/team',
    verifyEmailResend: '/auth/verify-email-resend',
    productDetails :(slug: string) => `/dashboard/audience/${slug}`,
    Doghouse: '/dashboard/doghouse', 
    Fetch_Earn: '/dashboard/fetchearn', 
    Muttmeter: '/dashboard/muttMeter', 
    Dog_Tags: '/dashboard/dogtags', 
    Governance:'/dashboard/ecosystem/governance',
    MuttArmyHub:'/dashboard/community/muttarmyhub',
    BurnTracker:'/dashboard/tokenomics/burntracker',
    Alpha_Barks: '/dashboard/alphabarks', 
    Top_Dogs: '/dashboard/topdogs', 
    Mutt_Trail: '/dashboard/mutttrail',  
    My_Kennel: '/dashboard/mykennel', 
    Help: '/dashboard/faq', 
    Dashboard: '/admin/dashboard',
    Transaction: '/admin/transaction',
    User: '/admin/user',
    Analtics: '/admin/analytics',
    Settings: '/admin/setting',
    Presale: '/admin/presale',
    Advanced: '/admin/advanced',

  },
  // signIn: '/auth/signin',
  landingPage: {
    home: '/',
    pricing: '/pricing',
    company: '/company',
    contactus: '/contactus',
    feature: '/feature',
    plan: '/feature/plan',
    demoFeature: '/feature/demopage',
  },
  vehicle :{
    dashboard:"/dashboard",
    newVehicle:'/dashboard/vehicle/viewVehicle',
    viewVehicleDetail:(slug:string)=>`/dashboard/vehicle/viewVehicle/${slug}`,
    editVehicleInfo: (slug: string) => `/dashboard/vehicle/viewVehicle/${slug}/edit`,
    addNewVehicle:'/dashboard/vehicle/addNewVehicle',
    usedVehicle:'/dashboard/vehicle/usedVehicle',
    shipmentVehicle:'/dashboard/vehicle/shipmentVehicle',
    auctionsheet:'/dashboard/auctionsheet',
    auctionsheetdetail:(slug:string)=>`/dashboard/auctionsheet/auctionSheetDetails/${slug}`,
    viewVehicleSpareParts:'/dashboard/vehicle/viewVehicleSpareParts',
    addSpareParts:'/dashboard/vehicle/addSpareParts',
    vehilceSparePartsDetails:(slug:string)=>`/dashboard/vehicle/viewVehicleSpareParts/${slug}`,
    editVehicleSpareParts:(slug:string)=>`/dashboard/vehicle/viewVehicleSpareParts/${slug}/edit`,
    staff:'/dashboard/roles-permissions/staff',
    expense:'/dashboard/expense',
    category:'/dashboard/expense/category',
    roles_permissions:"/dashboard/roles-permissions",
    reviews:'dashboard/vehicle/reviews',
    payment:'dashboard/vehicle/payment',
  },
  eCommerce: {
    dashboard: '/ecommerce',
    products: '/ecommerce/products',
    createProduct: '/ecommerce/products/create',
    productDetails: (slug: string) => `/ecommerce/products/${slug}`,
    demoPage: `/ecommerce/products/demoPage`,
    ediProduct: (slug: string) => `/ecommerce/products/${slug}/edit`,
    categories: '/ecommerce/categories',
    createCategory: '/ecommerce/categories/create',
    editCategory: (id: string) => `/ecommerce/categories/${id}/edit`,
    orders: '/ecommerce/orders',
    createOrder: '/ecommerce/orders/create',
    orderDetails: (id: string) => `/ecommerce/orders/${id}`,
    editOrder: (id: string) => `/ecommerce/orders/${id}/edit`,
    reviews: '/ecommerce/reviews',
    shop: '/ecommerce/shop',
    cart: '/ecommerce/cart',
    checkout: '/ecommerce/checkout',
    trackingId: (id: string) => `/ecommerce/tracking/${id}`,
  },
  searchAndFilter: {
    realEstate: '/search/real-estate',
    nft: '/search/nft',
    flight: '/search/flight',
  },
  support: {
    dashboard: '/support',
    inbox: '/support/inbox',
    supportCategory: (category: string) => `/support/inbox/${category}`,
    messageDetails: (id: string) => `/support/inbox/${id}`,
    snippets: '/support/snippets',
    createSnippet: '/support/snippets/create',
    viewSnippet: (id: string) => `/support/snippets/${id}`,
    editSnippet: (id: string) => `/support/snippets/${id}/edit`,
    templates: '/support/templates',
    createTemplate: '/support/templates/create',
    viewTemplate: (id: string) => `/support/templates/${id}`,
    editTemplate: (id: string) => `/support/templates/${id}/edit`,
  },
  logistics: {
    dashboard: '/logistics',
    shipmentList: '/logistics/shipments',
    customerProfile: '/logistics/customer-profile',
    createShipment: '/logistics/shipments/create',
    editShipment: (id: string) => `/logistics/shipments/${id}/edit`,
    shipmentDetails: (id: string) => `/logistics/shipments/${id}`,
    tracking: (id: string) => `/logistics/tracking/${id}`,
  },
  executive: {
    dashboard: '/dashboard/executive',
  },
  analytics: '/analytics',
  financial: {
    dashboard: '/financial',
  },
  file: {
    dashboard: '/dashboard',
    manager: '/file-manager',
    upload: '/file-manager/upload',
    create: '/file-manager/create',
  },
  pos: {
    index: '/point-of-sale',
  },
  eventCalendar: '/event-calendar',
  rolesPermissions: '/roles-permissions',
  invoice: {
    home: '/invoice',
    create: '/invoice/create',
    details: (id: string) => `/invoice/${id}`,
    edit: (id: string) => `/invoice/${id}/edit`,
  },
  widgets: {
    cards: '/widgets/cards',
    icons: '/widgets/icons',
    charts: '/widgets/charts',
    maps: '/widgets/maps',
    banners: '/widgets/banners',
  },
  tables: {
    basic: '/tables/basic',
    collapsible: '/tables/collapsible',
    enhanced: '/tables/enhanced',
    pagination: '/tables/pagination',
    search: '/tables/search',
    stickyHeader: '/tables/sticky-header',
  },
  // multiStep: '/multi-step',
  forms: {
    profileSettings: '/forms/profile-settings',
    notificationPreference: '/forms/profile-settings/notification',
    personalInformation: '/forms/profile-settings/profile',
    newsletter: '/forms/newsletter',
  },
  emailTemplates: '/email-templates',
  profile: '/profile',
  welcome: '/welcome',
  comingSoon: '/coming-soon',
  accessDenied: '/access-denied',
  notFound: '/not-found',
  maintenance: '/maintenance',
  blank: '/blank',
  auth: {
    signUp: '/auth/signup',
    signUp2: '/auth/sign-up-2',
    signUp3: '/auth/sign-up-3',
    signUp4: '/auth/sign-up-4',
    signUp5: '/auth/sign-up-5',
    // sign in
    signIn1: '/auth/sign-in-1',
    signIn2: '/auth/sign-in-2',
    signIn3: '/auth/sign-in-3',
    signIn4: '/auth/sign-in-4',
    signIn5: '/auth/sign-in-5',
    // forgot password
    forgotPassword: '/auth/forgot-password',
    forgotPassword2: '/auth/forgot-password-2',
    forgotPassword3: '/auth/forgot-password-3',
    forgotPassword4: '/auth/forgot-password-4',
    forgotPassword5: '/auth/forgot-password-5',
    // OTP
    otp1: '/auth/otp-1',
    otp2: '/auth/otp-2',
    otp3: '/auth/otp-3',
    otp4: '/auth/otp-4',
    otp5: '/auth/otp-5',
  },
};
